import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, createContext, useContext } from 'react'
import {Header, StyledSideMenu, MailContainer} from '../styles/globals'
import {SubContainer, MainBlock} from '../styles/dashboard'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Line } from "react-chartjs-2";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);



const labels = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
];

const data = {
  labels,
  datasets: [
    {
      label: "データ1",
      data: [10, 40, 30, 40, 50, 80, 120],
      borderColor: "rgb(255, 99, 132)",
      backgroundColor: "rgba(255, 99, 132, 0.5)",
    },
  ],
};


const Context = createContext({} as {
  isOpen: boolean
  setOpen: React.Dispatch<React.SetStateAction<boolean>>
})


const Home: NextPage = () => {
  const [isOpen, setOpen] = useState(false)
  let isLoad = true

  return (
    <>
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
      <Context.Provider value={{ isOpen, setOpen }}>
        <StyledSideMenu isOpen={isOpen}>
          <div className='sideMenuButton'>
            <input type='checkbox' id='sideMenuOpen'/>
            <label htmlFor='sideMenuOpen'
              data-load={isLoad}
              data-open={isOpen}
              onClick={() => setOpen(!isOpen)}>
              <div>
                <span/>
                <span/>
                <span/>
              </div>
            </label>
          </div>
          <div className='sideMenuBody' data-load={isLoad} data-open={isOpen}>
            <div className='sideMenuTitle'>
              HELLO!
            </div>
            <div className='sideMenuContents'>
              <div className='sideMenuContent_1'>
                <div className='bl_sideMenuContentName'>
                  <h2><span>HTT</span></h2>
                </div>
              </div>
              <div className='sideMenuContent_2' >
                <div className='bl_sideMenuContentName'>
                  <h2><span>利用規約</span></h2>
                </div>
              </div>
              <div className='sideMenuContent_3'>
                <div className='bl_sideMenuContentName'>
                  <h2><span>ヘルプ</span></h2>
                </div>
              </div>
              <div className='sideMenuContent_4'>
                <input type='checkbox' id='sideMenulink' />
                <label htmlFor='sideMenulink'></label>
                <div className='bl_sideMenuContentName'>
                  <span className='el_sideMenuListExtend'></span>
                  <h2>
                    <span>Link</span>
                  </h2>
                </div>
                <div className='bl_sideMenuList'>
                  <h3>STOP</h3>
                  <h3>DMM.COM</h3>
                  <h3>TEST.com</h3>
                  <h3>aaaa.com</h3>
                </div>
              </div>
            </div>
            <div className='sideMenuWave'>
              <svg className='waves' xmlns='http://www.w3.org/2000/svg' xlinkHref='http://www.w3.org/1999/xlink'
                viewBox='0 24 150 28' preserveAspectRatio='none' shapeRendering='auto'>
                <defs>
                  <path id='gentle-wave' d='M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z' />
                </defs>
                <g className='parallax'>
                  <use href='#gentle-wave' x='48' y='0' />
                  <use xlinkHref='#gentle-wave' x='48' y='3' />
                  <use xlinkHref='#gentle-wave' x='48' y='5' />
                  <use xlinkHref='#gentle-wave' x='48' y='7' />
                </g>
              </svg>
            </div>
          </div>
        </StyledSideMenu>
      </Context.Provider>

      <Header>
        <div>
          <div>
            <button></button>
          </div>
        </div>
        <div>
          <title></title>
        </div>
      </Header>


      <MailContainer>
        <SubContainer>
          <Line data={data} />
          <MainBlock></MainBlock>
        </SubContainer>
        <SubContainer>
          <MainBlock></MainBlock>
        </SubContainer>
      </MailContainer>
      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </>
  )
}

export default Home
